# encoding: utf-8
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|

  config.vm.box = 'ylinux-6'
  config.vm.box_url = "http://yo/ylinux6-vagrant-vbox"
  config.vm.hostname = "sandbox"

end
